"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-17

Hand-written rather than autogenerated: this sandbox has no network
access to run `alembic upgrade` against a live Postgres, so this
migration was written to exactly mirror app/models/*.py. Before Phase 3
starts, run `alembic upgrade head` against the real dev database and,
if you add/change any model afterward, prefer `alembic revision
--autogenerate` for all migrations from that point on — this one is the
exception because of the sandbox constraint, not the intended workflow.
"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None

EMBEDDING_DIM = 1536


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "services",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String(100), nullable=False, unique=True),
        sa.Column("description", sa.String(500), nullable=True),
    )
    op.create_index("ix_services_name", "services", ["name"])

    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("role", sa.String(50), nullable=False, server_default="engineer"),
    )

    op.create_table(
        "logs",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service_id", sa.Integer, sa.ForeignKey("services.id"), nullable=False),
        sa.Column("environment", sa.String(50), nullable=False, server_default="production"),
        sa.Column(
            "level",
            sa.Enum("DEBUG", "INFO", "WARNING", "ERROR", name="log_level"),
            nullable=False,
        ),
        sa.Column("endpoint", sa.String(200), nullable=True),
        sa.Column("error_type", sa.String(100), nullable=True),
        sa.Column("message", sa.String(2000), nullable=False),
        sa.Column("request_id", sa.String(100), nullable=True),
        sa.Column("trace_id", sa.String(100), nullable=True),
    )
    op.create_index("ix_logs_service_timestamp", "logs", ["service_id", "timestamp"])
    op.create_index("ix_logs_timestamp", "logs", ["timestamp"])
    op.create_index("ix_logs_error_type", "logs", ["error_type"])
    op.create_index("ix_logs_request_id", "logs", ["request_id"])
    op.create_index("ix_logs_trace_id", "logs", ["trace_id"])

    op.create_table(
        "metrics",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service_id", sa.Integer, sa.ForeignKey("services.id"), nullable=False),
        sa.Column("cpu_usage", sa.Float, nullable=False),
        sa.Column("memory_usage", sa.Float, nullable=False),
        sa.Column("request_count", sa.Integer, nullable=False),
        sa.Column("error_rate", sa.Float, nullable=False),
        sa.Column("latency_ms", sa.Float, nullable=False),
        sa.Column("db_connections", sa.Integer, nullable=False),
        sa.Column("queue_length", sa.Integer, nullable=False),
    )
    op.create_index("ix_metrics_service_timestamp", "metrics", ["service_id", "timestamp"])
    op.create_index("ix_metrics_timestamp", "metrics", ["timestamp"])

    op.create_table(
        "traces",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("trace_id", sa.String(100), nullable=False),
        sa.Column("request_id", sa.String(100), nullable=False),
        sa.Column("service_id", sa.Integer, sa.ForeignKey("services.id"), nullable=False),
        sa.Column("operation", sa.String(200), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Float, nullable=False),
        sa.Column("status", sa.Enum("ok", "error", name="trace_status"), nullable=False),
    )
    op.create_index("ix_traces_trace_id", "traces", ["trace_id"])
    op.create_index("ix_traces_service_start_time", "traces", ["service_id", "start_time"])
    op.create_index("ix_traces_request_id", "traces", ["request_id"])

    op.create_table(
        "deployments",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service_id", sa.Integer, sa.ForeignKey("services.id"), nullable=False),
        sa.Column("version", sa.String(50), nullable=False),
        sa.Column("commit_id", sa.String(100), nullable=False),
        sa.Column("change_summary", sa.String(1000), nullable=False),
    )
    op.create_index("ix_deployments_service_timestamp", "deployments", ["service_id", "timestamp"])
    op.create_index("ix_deployments_timestamp", "deployments", ["timestamp"])

    op.create_table(
        "code_changes",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("commit_id", sa.String(100), nullable=False),
        sa.Column("service_id", sa.Integer, sa.ForeignKey("services.id"), nullable=False),
        sa.Column("deployment_id", sa.Integer, sa.ForeignKey("deployments.id"), nullable=True),
        sa.Column("changed_file", sa.String(500), nullable=False),
        sa.Column(
            "change_type",
            sa.Enum("added", "modified", "removed", "config", name="change_type"),
            nullable=False,
        ),
        sa.Column("change_summary", sa.String(1000), nullable=False),
    )
    op.create_index("ix_code_changes_service_commit", "code_changes", ["service_id", "commit_id"])
    op.create_index("ix_code_changes_commit_id", "code_changes", ["commit_id"])

    op.create_table(
        "historical_incidents",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("title", sa.String(300), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="historical_incident_severity"),
            nullable=False,
        ),
        sa.Column("service_id", sa.Integer, sa.ForeignKey("services.id"), nullable=False),
        sa.Column("environment", sa.String(50), nullable=False, server_default="production"),
        sa.Column("symptoms", sa.Text, nullable=False),
        sa.Column("root_cause", sa.Text, nullable=False),
        sa.Column("resolution", sa.Text, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
    )

    op.create_table(
        "runbooks",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("title", sa.String(300), nullable=False),
        sa.Column("content_md", sa.Text, nullable=False),
        sa.Column("service_id", sa.Integer, sa.ForeignKey("services.id"), nullable=True),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
    )

    op.create_table(
        "incidents",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("title", sa.String(300), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="incident_severity"),
            nullable=False,
        ),
        sa.Column("service_id", sa.Integer, sa.ForeignKey("services.id"), nullable=False),
        sa.Column("environment", sa.String(50), nullable=False, server_default="production"),
        sa.Column(
            "status",
            sa.Enum("open", "investigating", "resolved", "closed", name="incident_status"),
            nullable=False,
            server_default="open",
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scenario_id", sa.String(100), nullable=True),
        sa.Column("description", sa.Text, nullable=True),
    )

    op.create_table(
        "investigations",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("incident_id", sa.Integer, sa.ForeignKey("incidents.id"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "completed", "failed", name="investigation_status"),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("plan_json", sa.JSON, nullable=True),
    )

    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("incident_id", sa.Integer, sa.ForeignKey("incidents.id"), nullable=False),
        sa.Column(
            "investigation_id", sa.Integer, sa.ForeignKey("investigations.id"), nullable=True
        ),
        sa.Column("source_type", sa.String(50), nullable=False),
        sa.Column("source_ref_id", sa.Integer, nullable=False),
        sa.Column("label", sa.String(300), nullable=False),
        sa.Column(
            "category", sa.Enum("fact", "evidence", name="evidence_category"), nullable=False
        ),
        sa.Column("payload_json", sa.JSON, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "hypotheses",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "investigation_id", sa.Integer, sa.ForeignKey("investigations.id"), nullable=False
        ),
        sa.Column("hypothesis_text", sa.String(1000), nullable=False),
        sa.Column("confidence", sa.Float, nullable=False),
        sa.Column(
            "supporting_evidence_ids",
            sa.ARRAY(sa.Integer),
            nullable=False,
            server_default="{}",
        ),
        sa.Column(
            "contradicting_evidence_ids",
            sa.ARRAY(sa.Integer),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("reasoning_summary", sa.Text, nullable=False),
        sa.Column("rank", sa.Integer, nullable=False),
    )

    op.create_table(
        "remediations",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "investigation_id", sa.Integer, sa.ForeignKey("investigations.id"), nullable=False
        ),
        sa.Column("hypothesis_id", sa.Integer, sa.ForeignKey("hypotheses.id"), nullable=False),
        sa.Column("action_type", sa.String(100), nullable=False),
        sa.Column("rationale", sa.Text, nullable=False),
        sa.Column(
            "risk_level", sa.Enum("low", "medium", "high", name="remediation_risk_level"),
            nullable=False,
        ),
        sa.Column("rollback_plan", sa.Text, nullable=False),
        sa.Column("requires_approval", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("approved_by", sa.Integer, sa.ForeignKey("users.id"), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "validation_runs",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "remediation_id", sa.Integer, sa.ForeignKey("remediations.id"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("passed", "failed", "not_validated", name="validation_status"),
            nullable=False,
            server_default="not_validated",
        ),
        sa.Column("tests_run_json", sa.JSON, nullable=True),
        sa.Column("results_json", sa.JSON, nullable=True),
        sa.Column("summary", sa.Text, nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("validation_runs")
    op.drop_table("remediations")
    op.drop_table("hypotheses")
    op.drop_table("evidence")
    op.drop_table("investigations")
    op.drop_table("incidents")
    op.drop_table("runbooks")
    op.drop_table("historical_incidents")
    op.drop_table("code_changes")
    op.drop_table("deployments")
    op.drop_table("traces")
    op.drop_table("metrics")
    op.drop_table("logs")
    op.drop_table("users")
    op.drop_table("services")

    for enum_name in (
        "validation_status",
        "remediation_risk_level",
        "evidence_category",
        "investigation_status",
        "incident_status",
        "incident_severity",
        "historical_incident_severity",
        "change_type",
        "trace_status",
        "log_level",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
